/*
 * generated by Xtext
 */
package escenariosCalidad;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XtextRuntimeModule extends escenariosCalidad.AbstractXtextRuntimeModule {

}
