/*
* generated by Xtext
*/
package escenariosCalidad;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XtextStandaloneSetup extends XtextStandaloneSetupGenerated{

	public static void doSetup() {
		new XtextStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

