/**
 *
 * $Id$
 */
package escenariosCalidad.validation;

import escenariosCalidad.Artefacto;
import escenariosCalidad.Escenario;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link escenariosCalidad.Arquitectura}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArquitecturaValidator {
	boolean validate();

	boolean validateEscenarios(EList<Escenario> value);
	boolean validateArtefactos(EList<Artefacto> value);
}
