/**
 *
 * $Id$
 */
package escenariosCalidad.validation;

import escenariosCalidad.Estimulo;
import escenariosCalidad.Fuente;
import escenariosCalidad.MedidaRespuesta;

/**
 * A sample validator interface for {@link escenariosCalidad.Escenario}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EscenarioValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateFuente(Fuente value);
	boolean validateEstimulo(Estimulo value);
	boolean validateMedida(MedidaRespuesta value);
}
