/**
 *
 * $Id$
 */
package escenariosCalidad.validation;

import escenariosCalidad.Metrica;
import escenariosCalidad.Operador;
import escenariosCalidad.Unidad;

/**
 * A sample validator interface for {@link escenariosCalidad.MedidaRespuesta}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MedidaRespuestaValidator {
	boolean validate();

	boolean validateMetrica(Metrica value);
	boolean validateValorEsperado(double value);
	boolean validateUnidad(Unidad value);
	boolean validateOperador(Operador value);
}
