/**
 * generated by Xtext
 */
package escenariosCalidad.ui.contentassist;

import escenariosCalidad.ui.contentassist.AbstractXtextProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class XtextProposalProvider extends AbstractXtextProposalProvider {
}
