/**
 * generated by Xtext
 */
package escenariosCalidad.validation;

import escenariosCalidad.validation.AbstractXtextValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class XtextValidator extends AbstractXtextValidator {
}
