/**
 * generated by Xtext
 */
package escenariosCalidad.serializer;

import escenariosCalidad.serializer.AbstractXtextSemanticSequencer;

@SuppressWarnings("all")
public class XtextSemanticSequencer extends AbstractXtextSemanticSequencer {
}
