/**
 * generated by Xtext
 */
package escenariosCalidad.serializer;

import escenariosCalidad.serializer.AbstractXtextSyntacticSequencer;

@SuppressWarnings("all")
public class XtextSyntacticSequencer extends AbstractXtextSyntacticSequencer {
}
