/*
 * generated by Xtext
 */
package escenariosCalidad.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XtextUiModule extends escenariosCalidad.ui.AbstractXtextUiModule {
	public XtextUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
