/*
* generated by Xtext
*/
package escenariosCalidad.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class XtextGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class TestElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Test");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTestAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTestKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cArquitecturasKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cArquitecturasAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cArquitecturasArquitecturaParserRuleCall_3_2_0 = (RuleCall)cArquitecturasAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cArquitecturasAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cArquitecturasArquitecturaParserRuleCall_3_3_1_0 = (RuleCall)cArquitecturasAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Test:
		//	{Test} "Test" "{" ("arquitecturas" "{" arquitecturas+=Arquitectura ("," arquitecturas+=Arquitectura)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{Test} "Test" "{" ("arquitecturas" "{" arquitecturas+=Arquitectura ("," arquitecturas+=Arquitectura)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{Test}
		public Action getTestAction_0() { return cTestAction_0; }

		//"Test"
		public Keyword getTestKeyword_1() { return cTestKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("arquitecturas" "{" arquitecturas+=Arquitectura ("," arquitecturas+=Arquitectura)* "}")?
		public Group getGroup_3() { return cGroup_3; }

		//"arquitecturas"
		public Keyword getArquitecturasKeyword_3_0() { return cArquitecturasKeyword_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }

		//arquitecturas+=Arquitectura
		public Assignment getArquitecturasAssignment_3_2() { return cArquitecturasAssignment_3_2; }

		//Arquitectura
		public RuleCall getArquitecturasArquitecturaParserRuleCall_3_2_0() { return cArquitecturasArquitecturaParserRuleCall_3_2_0; }

		//("," arquitecturas+=Arquitectura)*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//arquitecturas+=Arquitectura
		public Assignment getArquitecturasAssignment_3_3_1() { return cArquitecturasAssignment_3_3_1; }

		//Arquitectura
		public RuleCall getArquitecturasArquitecturaParserRuleCall_3_3_1_0() { return cArquitecturasArquitecturaParserRuleCall_3_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class ArquitecturaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Arquitectura");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cArquitecturaAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cArquitecturaKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cEscenariosKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cEscenariosAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cEscenariosEscenarioParserRuleCall_3_2_0 = (RuleCall)cEscenariosAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cEscenariosAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cEscenariosEscenarioParserRuleCall_3_3_1_0 = (RuleCall)cEscenariosAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cArtefactosKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cArtefactosAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cArtefactosArtefactoParserRuleCall_4_2_0 = (RuleCall)cArtefactosAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cArtefactosAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cArtefactosArtefactoParserRuleCall_4_3_1_0 = (RuleCall)cArtefactosAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Arquitectura:
		//	{Arquitectura} "Arquitectura" "{" ("escenarios" "{" escenarios+=Escenario ("," escenarios+=Escenario)* "}")?
		//	("artefactos" "{" artefactos+=Artefacto ("," artefactos+=Artefacto)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{Arquitectura} "Arquitectura" "{" ("escenarios" "{" escenarios+=Escenario ("," escenarios+=Escenario)* "}")?
		//("artefactos" "{" artefactos+=Artefacto ("," artefactos+=Artefacto)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{Arquitectura}
		public Action getArquitecturaAction_0() { return cArquitecturaAction_0; }

		//"Arquitectura"
		public Keyword getArquitecturaKeyword_1() { return cArquitecturaKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("escenarios" "{" escenarios+=Escenario ("," escenarios+=Escenario)* "}")?
		public Group getGroup_3() { return cGroup_3; }

		//"escenarios"
		public Keyword getEscenariosKeyword_3_0() { return cEscenariosKeyword_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }

		//escenarios+=Escenario
		public Assignment getEscenariosAssignment_3_2() { return cEscenariosAssignment_3_2; }

		//Escenario
		public RuleCall getEscenariosEscenarioParserRuleCall_3_2_0() { return cEscenariosEscenarioParserRuleCall_3_2_0; }

		//("," escenarios+=Escenario)*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//escenarios+=Escenario
		public Assignment getEscenariosAssignment_3_3_1() { return cEscenariosAssignment_3_3_1; }

		//Escenario
		public RuleCall getEscenariosEscenarioParserRuleCall_3_3_1_0() { return cEscenariosEscenarioParserRuleCall_3_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }

		//("artefactos" "{" artefactos+=Artefacto ("," artefactos+=Artefacto)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"artefactos"
		public Keyword getArtefactosKeyword_4_0() { return cArtefactosKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//artefactos+=Artefacto
		public Assignment getArtefactosAssignment_4_2() { return cArtefactosAssignment_4_2; }

		//Artefacto
		public RuleCall getArtefactosArtefactoParserRuleCall_4_2_0() { return cArtefactosArtefactoParserRuleCall_4_2_0; }

		//("," artefactos+=Artefacto)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//artefactos+=Artefacto
		public Assignment getArtefactosAssignment_4_3_1() { return cArtefactosAssignment_4_3_1; }

		//Artefacto
		public RuleCall getArtefactosArtefactoParserRuleCall_4_3_1_0() { return cArtefactosArtefactoParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class EscenarioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Escenario");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEscenarioKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIdKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cIdAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_2_1_0 = (RuleCall)cIdAssignment_2_1.eContents().get(0);
		private final Keyword cFuenteKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFuenteAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFuenteFuenteParserRuleCall_4_0 = (RuleCall)cFuenteAssignment_4.eContents().get(0);
		private final Keyword cEstimuloKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cEstimuloAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cEstimuloEstimuloParserRuleCall_6_0 = (RuleCall)cEstimuloAssignment_6.eContents().get(0);
		private final Keyword cMedidaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cMedidaAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cMedidaMedidaRespuestaParserRuleCall_8_0 = (RuleCall)cMedidaAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Escenario:
		//	"Escenario" "{" ("id" id=EString)? "fuente" fuente=Fuente "estimulo" estimulo=Estimulo "medida"
		//	medida=MedidaRespuesta "}";
		public ParserRule getRule() { return rule; }

		//"Escenario" "{" ("id" id=EString)? "fuente" fuente=Fuente "estimulo" estimulo=Estimulo "medida" medida=MedidaRespuesta
		//"}"
		public Group getGroup() { return cGroup; }

		//"Escenario"
		public Keyword getEscenarioKeyword_0() { return cEscenarioKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//("id" id=EString)?
		public Group getGroup_2() { return cGroup_2; }

		//"id"
		public Keyword getIdKeyword_2_0() { return cIdKeyword_2_0; }

		//id=EString
		public Assignment getIdAssignment_2_1() { return cIdAssignment_2_1; }

		//EString
		public RuleCall getIdEStringParserRuleCall_2_1_0() { return cIdEStringParserRuleCall_2_1_0; }

		//"fuente"
		public Keyword getFuenteKeyword_3() { return cFuenteKeyword_3; }

		//fuente=Fuente
		public Assignment getFuenteAssignment_4() { return cFuenteAssignment_4; }

		//Fuente
		public RuleCall getFuenteFuenteParserRuleCall_4_0() { return cFuenteFuenteParserRuleCall_4_0; }

		//"estimulo"
		public Keyword getEstimuloKeyword_5() { return cEstimuloKeyword_5; }

		//estimulo=Estimulo
		public Assignment getEstimuloAssignment_6() { return cEstimuloAssignment_6; }

		//Estimulo
		public RuleCall getEstimuloEstimuloParserRuleCall_6_0() { return cEstimuloEstimuloParserRuleCall_6_0; }

		//"medida"
		public Keyword getMedidaKeyword_7() { return cMedidaKeyword_7; }

		//medida=MedidaRespuesta
		public Assignment getMedidaAssignment_8() { return cMedidaAssignment_8; }

		//MedidaRespuesta
		public RuleCall getMedidaMedidaRespuestaParserRuleCall_8_0() { return cMedidaMedidaRespuestaParserRuleCall_8_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class ArtefactoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Artefacto");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cArtefactoAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cArtefactoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cUrlKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cUrlAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cUrlEStringParserRuleCall_3_1_0 = (RuleCall)cUrlAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Artefacto:
		//	{Artefacto} "Artefacto" "{" ("url" url=EString)? "}";
		public ParserRule getRule() { return rule; }

		//{Artefacto} "Artefacto" "{" ("url" url=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{Artefacto}
		public Action getArtefactoAction_0() { return cArtefactoAction_0; }

		//"Artefacto"
		public Keyword getArtefactoKeyword_1() { return cArtefactoKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("url" url=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"url"
		public Keyword getUrlKeyword_3_0() { return cUrlKeyword_3_0; }

		//url=EString
		public Assignment getUrlAssignment_3_1() { return cUrlAssignment_3_1; }

		//EString
		public RuleCall getUrlEStringParserRuleCall_3_1_0() { return cUrlEStringParserRuleCall_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class FuenteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Fuente");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFuenteAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFuenteKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Fuente:
		//	{Fuente} "Fuente" name=EString;
		public ParserRule getRule() { return rule; }

		//{Fuente} "Fuente" name=EString
		public Group getGroup() { return cGroup; }

		//{Fuente}
		public Action getFuenteAction_0() { return cFuenteAction_0; }

		//"Fuente"
		public Keyword getFuenteKeyword_1() { return cFuenteKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}

	public class EstimuloElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Estimulo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEstimuloKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cArtefactoKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cArtefactoAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cArtefactoArtefactoCrossReference_3_0 = (CrossReference)cArtefactoAssignment_3.eContents().get(0);
		private final RuleCall cArtefactoArtefactoEStringParserRuleCall_3_0_1 = (RuleCall)cArtefactoArtefactoCrossReference_3_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Estimulo:
		//	"Estimulo" "{" "artefacto" artefacto=[Artefacto|EString] "}";
		public ParserRule getRule() { return rule; }

		//"Estimulo" "{" "artefacto" artefacto=[Artefacto|EString] "}"
		public Group getGroup() { return cGroup; }

		//"Estimulo"
		public Keyword getEstimuloKeyword_0() { return cEstimuloKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"artefacto"
		public Keyword getArtefactoKeyword_2() { return cArtefactoKeyword_2; }

		//artefacto=[Artefacto|EString]
		public Assignment getArtefactoAssignment_3() { return cArtefactoAssignment_3; }

		//[Artefacto|EString]
		public CrossReference getArtefactoArtefactoCrossReference_3_0() { return cArtefactoArtefactoCrossReference_3_0; }

		//EString
		public RuleCall getArtefactoArtefactoEStringParserRuleCall_3_0_1() { return cArtefactoArtefactoEStringParserRuleCall_3_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class MedidaRespuestaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MedidaRespuesta");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMedidaRespuestaAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMedidaRespuestaKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cMetricaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cMetricaAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cMetricaMetricaEnumRuleCall_3_1_0 = (RuleCall)cMetricaAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cValorEsperadoKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cValorEsperadoAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cValorEsperadoEDoubleParserRuleCall_4_1_0 = (RuleCall)cValorEsperadoAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cUnidadKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cUnidadAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cUnidadUnidadEnumRuleCall_5_1_0 = (RuleCall)cUnidadAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cOperadorKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cOperadorAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cOperadorOperadorEnumRuleCall_6_1_0 = (RuleCall)cOperadorAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//MedidaRespuesta:
		//	{MedidaRespuesta} "MedidaRespuesta" "{" ("metrica" metrica=Metrica)? ("valorEsperado" valorEsperado=EDouble)?
		//	("unidad" unidad=Unidad)? ("operador" operador=Operador)? "}";
		public ParserRule getRule() { return rule; }

		//{MedidaRespuesta} "MedidaRespuesta" "{" ("metrica" metrica=Metrica)? ("valorEsperado" valorEsperado=EDouble)? ("unidad"
		//unidad=Unidad)? ("operador" operador=Operador)? "}"
		public Group getGroup() { return cGroup; }

		//{MedidaRespuesta}
		public Action getMedidaRespuestaAction_0() { return cMedidaRespuestaAction_0; }

		//"MedidaRespuesta"
		public Keyword getMedidaRespuestaKeyword_1() { return cMedidaRespuestaKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("metrica" metrica=Metrica)?
		public Group getGroup_3() { return cGroup_3; }

		//"metrica"
		public Keyword getMetricaKeyword_3_0() { return cMetricaKeyword_3_0; }

		//metrica=Metrica
		public Assignment getMetricaAssignment_3_1() { return cMetricaAssignment_3_1; }

		//Metrica
		public RuleCall getMetricaMetricaEnumRuleCall_3_1_0() { return cMetricaMetricaEnumRuleCall_3_1_0; }

		//("valorEsperado" valorEsperado=EDouble)?
		public Group getGroup_4() { return cGroup_4; }

		//"valorEsperado"
		public Keyword getValorEsperadoKeyword_4_0() { return cValorEsperadoKeyword_4_0; }

		//valorEsperado=EDouble
		public Assignment getValorEsperadoAssignment_4_1() { return cValorEsperadoAssignment_4_1; }

		//EDouble
		public RuleCall getValorEsperadoEDoubleParserRuleCall_4_1_0() { return cValorEsperadoEDoubleParserRuleCall_4_1_0; }

		//("unidad" unidad=Unidad)?
		public Group getGroup_5() { return cGroup_5; }

		//"unidad"
		public Keyword getUnidadKeyword_5_0() { return cUnidadKeyword_5_0; }

		//unidad=Unidad
		public Assignment getUnidadAssignment_5_1() { return cUnidadAssignment_5_1; }

		//Unidad
		public RuleCall getUnidadUnidadEnumRuleCall_5_1_0() { return cUnidadUnidadEnumRuleCall_5_1_0; }

		//("operador" operador=Operador)?
		public Group getGroup_6() { return cGroup_6; }

		//"operador"
		public Keyword getOperadorKeyword_6_0() { return cOperadorKeyword_6_0; }

		//operador=Operador
		public Assignment getOperadorAssignment_6_1() { return cOperadorAssignment_6_1; }

		//Operador
		public RuleCall getOperadorOperadorEnumRuleCall_6_1_0() { return cOperadorOperadorEnumRuleCall_6_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble returns ecore::EDouble:
		//	"-"? INT? "." INT (("E" | "e") "-"? INT)?;
		public ParserRule getRule() { return rule; }

		//"-"? INT? "." INT (("E" | "e") "-"? INT)?
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }

		//"."
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }

		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }

		//(("E" | "e") "-"? INT)?
		public Group getGroup_4() { return cGroup_4; }

		//"E" | "e"
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }

		//"E"
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }

		//"e"
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }

		//"-"?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }

		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	
	
	public class MetricaElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Metrica");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cLatencyEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cLatencyLatencyKeyword_0_0 = (Keyword)cLatencyEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cThroughputEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cThroughputThroughputKeyword_1_0 = (Keyword)cThroughputEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cErrorPercentageEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cErrorPercentageErrorPercentageKeyword_2_0 = (Keyword)cErrorPercentageEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cResponseCodeEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cResponseCodeResponseCodeKeyword_3_0 = (Keyword)cResponseCodeEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum Metrica:
		//	latency | throughput | errorPercentage | responseCode;
		public EnumRule getRule() { return rule; }

		//latency | throughput | errorPercentage | responseCode
		public Alternatives getAlternatives() { return cAlternatives; }

		//latency
		public EnumLiteralDeclaration getLatencyEnumLiteralDeclaration_0() { return cLatencyEnumLiteralDeclaration_0; }

		//"latency"
		public Keyword getLatencyLatencyKeyword_0_0() { return cLatencyLatencyKeyword_0_0; }

		//throughput
		public EnumLiteralDeclaration getThroughputEnumLiteralDeclaration_1() { return cThroughputEnumLiteralDeclaration_1; }

		//"throughput"
		public Keyword getThroughputThroughputKeyword_1_0() { return cThroughputThroughputKeyword_1_0; }

		//errorPercentage
		public EnumLiteralDeclaration getErrorPercentageEnumLiteralDeclaration_2() { return cErrorPercentageEnumLiteralDeclaration_2; }

		//"errorPercentage"
		public Keyword getErrorPercentageErrorPercentageKeyword_2_0() { return cErrorPercentageErrorPercentageKeyword_2_0; }

		//responseCode
		public EnumLiteralDeclaration getResponseCodeEnumLiteralDeclaration_3() { return cResponseCodeEnumLiteralDeclaration_3; }

		//"responseCode"
		public Keyword getResponseCodeResponseCodeKeyword_3_0() { return cResponseCodeResponseCodeKeyword_3_0; }
	}

	public class UnidadElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Unidad");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSegundosEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSegundosSegundosKeyword_0_0 = (Keyword)cSegundosEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMsEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMsMsKeyword_1_0 = (Keyword)cMsEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cRequestEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cRequestRequestKeyword_2_0 = (Keyword)cRequestEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Unidad:
		//	segundos | ms | request;
		public EnumRule getRule() { return rule; }

		//segundos | ms | request
		public Alternatives getAlternatives() { return cAlternatives; }

		//segundos
		public EnumLiteralDeclaration getSegundosEnumLiteralDeclaration_0() { return cSegundosEnumLiteralDeclaration_0; }

		//"segundos"
		public Keyword getSegundosSegundosKeyword_0_0() { return cSegundosSegundosKeyword_0_0; }

		//ms
		public EnumLiteralDeclaration getMsEnumLiteralDeclaration_1() { return cMsEnumLiteralDeclaration_1; }

		//"ms"
		public Keyword getMsMsKeyword_1_0() { return cMsMsKeyword_1_0; }

		//request
		public EnumLiteralDeclaration getRequestEnumLiteralDeclaration_2() { return cRequestEnumLiteralDeclaration_2; }

		//"request"
		public Keyword getRequestRequestKeyword_2_0() { return cRequestRequestKeyword_2_0; }
	}

	public class OperadorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Operador");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cGTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cGTGTKeyword_0_0 = (Keyword)cGTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cLTEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cLTLTKeyword_1_0 = (Keyword)cLTEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cGTEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cGTEGTEKeyword_2_0 = (Keyword)cGTEEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cLTEEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cLTELTEKeyword_3_0 = (Keyword)cLTEEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cEEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cEEKeyword_4_0 = (Keyword)cEEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum Operador:
		//	GT | LT | GTE | LTE | E;
		public EnumRule getRule() { return rule; }

		//GT | LT | GTE | LTE | E
		public Alternatives getAlternatives() { return cAlternatives; }

		//GT
		public EnumLiteralDeclaration getGTEnumLiteralDeclaration_0() { return cGTEnumLiteralDeclaration_0; }

		//"GT"
		public Keyword getGTGTKeyword_0_0() { return cGTGTKeyword_0_0; }

		//LT
		public EnumLiteralDeclaration getLTEnumLiteralDeclaration_1() { return cLTEnumLiteralDeclaration_1; }

		//"LT"
		public Keyword getLTLTKeyword_1_0() { return cLTLTKeyword_1_0; }

		//GTE
		public EnumLiteralDeclaration getGTEEnumLiteralDeclaration_2() { return cGTEEnumLiteralDeclaration_2; }

		//"GTE"
		public Keyword getGTEGTEKeyword_2_0() { return cGTEGTEKeyword_2_0; }

		//LTE
		public EnumLiteralDeclaration getLTEEnumLiteralDeclaration_3() { return cLTEEnumLiteralDeclaration_3; }

		//"LTE"
		public Keyword getLTELTEKeyword_3_0() { return cLTELTEKeyword_3_0; }

		//E
		public EnumLiteralDeclaration getEEnumLiteralDeclaration_4() { return cEEnumLiteralDeclaration_4; }

		//"E"
		public Keyword getEEKeyword_4_0() { return cEEKeyword_4_0; }
	}
	
	private final TestElements pTest;
	private final ArquitecturaElements pArquitectura;
	private final EscenarioElements pEscenario;
	private final ArtefactoElements pArtefacto;
	private final EStringElements pEString;
	private final FuenteElements pFuente;
	private final EstimuloElements pEstimulo;
	private final MedidaRespuestaElements pMedidaRespuesta;
	private final MetricaElements unknownRuleMetrica;
	private final EDoubleElements pEDouble;
	private final UnidadElements unknownRuleUnidad;
	private final OperadorElements unknownRuleOperador;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public XtextGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pTest = new TestElements();
		this.pArquitectura = new ArquitecturaElements();
		this.pEscenario = new EscenarioElements();
		this.pArtefacto = new ArtefactoElements();
		this.pEString = new EStringElements();
		this.pFuente = new FuenteElements();
		this.pEstimulo = new EstimuloElements();
		this.pMedidaRespuesta = new MedidaRespuestaElements();
		this.unknownRuleMetrica = new MetricaElements();
		this.pEDouble = new EDoubleElements();
		this.unknownRuleUnidad = new UnidadElements();
		this.unknownRuleOperador = new OperadorElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("escenariosCalidad.Xtext".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Test:
	//	{Test} "Test" "{" ("arquitecturas" "{" arquitecturas+=Arquitectura ("," arquitecturas+=Arquitectura)* "}")? "}";
	public TestElements getTestAccess() {
		return pTest;
	}
	
	public ParserRule getTestRule() {
		return getTestAccess().getRule();
	}

	//Arquitectura:
	//	{Arquitectura} "Arquitectura" "{" ("escenarios" "{" escenarios+=Escenario ("," escenarios+=Escenario)* "}")?
	//	("artefactos" "{" artefactos+=Artefacto ("," artefactos+=Artefacto)* "}")? "}";
	public ArquitecturaElements getArquitecturaAccess() {
		return pArquitectura;
	}
	
	public ParserRule getArquitecturaRule() {
		return getArquitecturaAccess().getRule();
	}

	//Escenario:
	//	"Escenario" "{" ("id" id=EString)? "fuente" fuente=Fuente "estimulo" estimulo=Estimulo "medida"
	//	medida=MedidaRespuesta "}";
	public EscenarioElements getEscenarioAccess() {
		return pEscenario;
	}
	
	public ParserRule getEscenarioRule() {
		return getEscenarioAccess().getRule();
	}

	//Artefacto:
	//	{Artefacto} "Artefacto" "{" ("url" url=EString)? "}";
	public ArtefactoElements getArtefactoAccess() {
		return pArtefacto;
	}
	
	public ParserRule getArtefactoRule() {
		return getArtefactoAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//Fuente:
	//	{Fuente} "Fuente" name=EString;
	public FuenteElements getFuenteAccess() {
		return pFuente;
	}
	
	public ParserRule getFuenteRule() {
		return getFuenteAccess().getRule();
	}

	//Estimulo:
	//	"Estimulo" "{" "artefacto" artefacto=[Artefacto|EString] "}";
	public EstimuloElements getEstimuloAccess() {
		return pEstimulo;
	}
	
	public ParserRule getEstimuloRule() {
		return getEstimuloAccess().getRule();
	}

	//MedidaRespuesta:
	//	{MedidaRespuesta} "MedidaRespuesta" "{" ("metrica" metrica=Metrica)? ("valorEsperado" valorEsperado=EDouble)?
	//	("unidad" unidad=Unidad)? ("operador" operador=Operador)? "}";
	public MedidaRespuestaElements getMedidaRespuestaAccess() {
		return pMedidaRespuesta;
	}
	
	public ParserRule getMedidaRespuestaRule() {
		return getMedidaRespuestaAccess().getRule();
	}

	//enum Metrica:
	//	latency | throughput | errorPercentage | responseCode;
	public MetricaElements getMetricaAccess() {
		return unknownRuleMetrica;
	}
	
	public EnumRule getMetricaRule() {
		return getMetricaAccess().getRule();
	}

	//EDouble returns ecore::EDouble:
	//	"-"? INT? "." INT (("E" | "e") "-"? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}

	//enum Unidad:
	//	segundos | ms | request;
	public UnidadElements getUnidadAccess() {
		return unknownRuleUnidad;
	}
	
	public EnumRule getUnidadRule() {
		return getUnidadAccess().getRule();
	}

	//enum Operador:
	//	GT | LT | GTE | LTE | E;
	public OperadorElements getOperadorAccess() {
		return unknownRuleOperador;
	}
	
	public EnumRule getOperadorRule() {
		return getOperadorAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
